#!/bin/sh
set -e

usage () {
  echo "Usage: [VARIABLE...] $(basename $0) libname"
  echo "  libname     Name of the .a library"
  echo ""
  echo "  VARIABLEs are:"
  echo "    ARCHS     Only build for specific architectures. Default is:"
  echo "                armv7|armv7s|arm64|i686|x86_64"
  echo "    PREFIX    Installation prefix for framework and static files."
  echo ""
  echo "  All additional parameters are passed to the configure script."
  exit 1
}

# Sanity checks
if [ "$#" -lt 1 ]; then
  usage
fi

ICONFIGURE="$(dirname $0)/iconfigure"

LIBARCHIVE=$1

shift 1

if [ -z "$LIB_OUTPUT" ]; then
  LIB_OUTPUT="$(pwd)"
fi

if [ -z "$PREFIX" ]; then
  PREFIX="$(pwd)"
fi

STATICDIR="$PREFIX/Static"

if [ -z "$ARCHS" ]; then
  case $OS in
    macos | macosx )
      ARCHS="x86_64"
      ;;
    tvos )
      ARCHS="x86_64 arm64"
      ;;
    watchos )
      ARCHS="i386 armv7 armv7k"
      ;;
    ios )
      ARCHS="i386 x86_64 armv7 armv7s arm64"
      ;;
    * )
      OS=ios
      ARCHS="i386 x86_64 armv7 armv7s arm64"
      ;;
  esac
fi

# Build all architectures
for ARCH in $ARCHS; do
  make distclean || true
  PREFIX="$STATICDIR/$ARCH-$OS" $ICONFIGURE $ARCH $@
  make
  make install
done

# Install header files
PREFIX="$STATICDIR/$ARCH-$OS" $ICONFIGURE $ARCH --includedir="$LIB_OUTPUT/../include" $@
make
make install

# Create multiarch archive
for ARCH in $ARCHS; do
  LIPOARCHS="$LIPOARCHS -arch $ARCH $STATICDIR/$ARCH-$OS/lib/$LIBARCHIVE.a"
done
lipo -create -output "$LIB_OUTPUT/$LIBARCHIVE-$OS.a" $LIPOARCHS

echo "Success!"
echo "Built $FRAMEWORK for architectures: $ARCHS"

