#!/bin/sh
set -e

usage () {
  echo "Usage: [VARIABLE...] $(basename $0) architecture"
  echo ""
  echo "  architecture   Target architecture. [armv7|armv7s|arm64|i386|x86_64]"
  echo ""
  echo "  VARIABLEs are:"
  echo "    SDKVERSION   Target a specific SDK version."
  echo "    PREFIX       Custom install prefix, useful for local installs."
  echo "    CHOST        Configure host, set if not deducable by ARCH."
  echo "    SDK          SDK target, set if not deducable by ARCH. [iphoneos|iphonesimulator]"
  echo ""
  echo "    CFLAGS CPPFLAGS CXXFLAGS LDFLAGS PKG_CONFIG_PATH"
  echo ""
  echo "  All additional parameters are passed to the configure script."
  exit 1
}

# Sanity checks
if [ "$#" -lt 1 ]; then
  echo "Please supply an architecture name."
  usage
fi

if [ ! -x "./configure" ] ; then
  echo "No configure script found."
  usage
fi

# Build architecture
export ARCH=$1

# Export supplied CHOST or deduce by ARCH
if [ ! -z "$CHOST" ]; then
  export CHOST
else
  case $ARCH in
    armv7 | armv7k | armv7s )
      export CHOST=arm-apple-darwin*
      ;;
    arm64 )
      export CHOST=aarch64-apple-darwin*
      ;;
    i386 | x86_64 )
      export CHOST=$ARCH-apple-darwin*
      ;;
    * )
      usage
      ;;
  esac
fi

# Export supplied SDK or deduce by ARCH
if [ ! -z "$SDK" ]; then
  export SDK
else
  case $OS in
    macos | macosx )
      export SDK=macosx
      ;;
    tvos )
      case $ARCH in
        i386 | x86_64 )
          export SDK=appletvsimulator
          ;;
        * )
          export SDK=appletvos
          ;;
       esac
       ;;
    watchos )
      case $ARCH in
        i386 | x86_64 )
          export SDK=watchsimulator
          ;;
        * )
          export SDK=watchos
          ;;
       esac
       ;;
    ios )
      case $ARCH in
        i386 | x86_64 )
          export SDK=iphonesimulator
          ;;
        * )
          export SDK=iphoneos
          ;;
      esac
      ;;
    * )
      case $ARCH in
        i386 | x86_64 )
          export SDK=iphonesimulator
          ;;
        * )
          export SDK=iphoneos
          ;;
      esac
      ;;
  esac
fi

# Export supplied SDKVERSION or use system default
if [ ! -z "$SDKVERSION" ]; then
  SDKNAME=$(basename $(xcrun --sdk $SDK --show-sdk-platform-path) .platform)
  export SDKVERSION
  export SDKROOT=$(xcrun --sdk $SDK --show-sdk-platform-path)"/Developer/SDKs/$SDKNAME.$SDKVERSION.sdk"
else
  export SDKVERSION=$(xcrun --sdk $SDK --show-sdk-version) # current version
  export SDKROOT=$(xcrun --sdk $SDK --show-sdk-path) # current version
fi

# Export supplied PREFIX or use default
if [ ! -z "$PREFIX" ]; then
  export PREFIX
fi

if [ ! -z "$MINSDKVERSION" ]; then
  export MINSDKVERSION
else
  export MINSDKVERSION="$SDKVERSION"
fi

# Binaries
if [ "$USECLANG" -eq 1 ]; then
  export CC=$(xcrun --sdk $SDK --find clang)
  export CPP=$(xcrun --sdk $SDK --find clang)" -E"
  export CXX=$(xcrun --sdk $SDK --find clang++)
  export LD=$(xcrun --sdk $SDK --find ld)
else
  export CC=$(xcrun --sdk $SDK --find gcc)
  export CPP=$(xcrun --sdk $SDK --find gcc)" -E"
  export CXX=$(xcrun --sdk $SDK --find g++)
  export LD=$(xcrun --sdk $SDK --find ld)
fi

# Flags
export CFLAGS="$CFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include -m$SDK-version-min=$MINSDKVERSION"
export CPPFLAGS="$CPPFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include -m$SDK-version-min=$MINSDKVERSION"
export CXXFLAGS="$CXXFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include"
export LDFLAGS="$LDFLAGS -arch $ARCH -isysroot $SDKROOT -L$PREFIX/lib"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH":"$SDKROOT/usr/lib/pkgconfig":"$PREFIX/lib/pkgconfig"

# Remove script parameters
shift 1

# Run configure
./configure \
	--prefix="$PREFIX" \
	--host="$CHOST" \
	--enable-static \
	--disable-shared \
	$@
